// Generated by dia2code
#ifndef CASE__H
#define CASE__H
#include <list>
using std::list;
/// class Case - 
class Case {
  // Attributes
public:
  list<int> Coordonnee;
  bool occupee;
  // Operations
public:
  list<int> GetCoordonees ();
  void CreateCase (list<int> coord, bool occupe);
  bool GetOccupe ();
  void SetOccupe (bool etat);
  // Setters and Getters
};

#endif
