// Generated by dia2code
#ifndef INSECT__H
#define INSECT__H
#include <list>
#include <string>
using std::list;

#include "Scarabe.h"
#include "Abeille.h"
#include "Araigné.h"
#include "Cocinelle.h"
#include "Grillon.h"
#include "Sauterelle.h"
#include "Moustique.h"
#include "Fourmi.h"

/// class Insect - 
class Insect : public Scarabe, public Abeille, public Cocinelle, public Grillon, public Araigné, public Sauterelle, public Moustique, public Fourmi {
  // Attributes
public:
  std::string nom;
  std::string couleur;
  list<int> position;
  /// Certains pions peuvent monter sur d'autres donc le niveau 0 correspond au sol et le niveau 1 est celui du dessus
  int niveau;
  // Operations
public:
  void Select_Insect ();
  void Update_Position_Insecte ();
  list<int> getpos ();
  list<list<int>> Placement_possible_Insecte ();
  virtual list<list<int>> Deplacement_possible_Insecte () = 0;
  std::string GetNom ();
  std::string GetCouleur ();
  list<int> GetPosition ();
  int GetNiveau ();
  void SetPosition (list<int> coord);
  void SetNiveau (int niveau);
  // Setters and Getters
};

#endif
