// Generated by dia2code
#ifndef JEU__H
#define JEU__H
#include <list>
using std::list;
#include "GameStatus.h"
#include "Insect.h"
#include "Plateau.h"


/// class Jeu - 
class Jeu {
  // Associations
  // Attributes
public:
  GameStatus etat;
  int nbTours;
  list<Insect> ListeAllInsect;
  Plateau plateau;
  // Operations
public:
  bool IsBeeACircled ();
  bool IsBeeBCircled ();
  void UpdateEtat ();
  void IncrementeTour ();
  void Affiche_coups_possibles (list<int> ListeCoups);
  void SetEtat (GameStatus status);
  GameStatus GetEtat ();
  int GetNbTours ();
  void SetNbTours (int param);
  list<Insect> GetAllInsects ();
  void AppendListInsect (Insect insecte);
  Plateau GetPlateau ();
  // Setters and Getters
};

#endif
