// Generated by dia2code
#ifndef PLATEAU__H
#define PLATEAU__H
#include <list>
using std::list;


/// class Plateau - 
class Plateau {
  // Associations
  // Attributes
public:
  int Longueur;
  int Largeur;
  list<list<int>> ListeCoordonees;
  // Operations
public:
  void creer_plateau (int longueur, int largeur);
  int GetLongueur ();
  int GetLargeur ();
  list<list<int>> GetCoordonnees ();
  // Setters and Getters
};

#endif
